# Experiment 8: Test of Hypothesis for Large Samples

**Date:** 

## Experiment Title
Test of hypothesis for large samples

## Aim
To study hypothesis testing for proportion and mean for large samples.

## Software
- Google Colab
- Jupyter Notebook
- Visual Studio Code

## Theory
### Hypothesis Testing for Proportions (Large Samples)

For proportions, when sample size $n$ is large (typically $n \geq 30$), we use the **z-test**:

**Test Statistic:** 
$$z = \frac{p - P}{\sqrt{\frac{P(1-P)}{n}}}$$

where:
- $p$ = sample proportion
- $P$ = hypothesized population proportion
- $n$ = sample size

**Confidence Interval for Proportion:**
$$CI = p \pm z_{\alpha/2} \sqrt{\frac{p(1-p)}{n}}$$

### Hypothesis Testing for Means (Large Samples)

For means, when sample size $n$ is large (typically $n \geq 30$), we use the **z-test**:

**Test Statistic:**
$$z = \frac{\bar{x} - \mu}{\sigma/\sqrt{n}}$$

where:
- $\bar{x}$ = sample mean
- $\mu$ = hypothesized population mean
- $\sigma$ = population standard deviation (or sample standard deviation for large samples)
- $n$ = sample size

**Confidence Interval for Mean:**
$$CI = \bar{x} \pm z_{\alpha/2} \frac{\sigma}{\sqrt{n}}$$

### Decision Rule
- If $|z| > z_{\alpha/2}$ (two-tailed) or $z > z_{\alpha}$ (one-tailed), **reject** the null hypothesis
- Otherwise, **fail to reject** the null hypothesis

In [28]:
# Import Required Libraries
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import norm, t
import math

# Set display options
np.set_printoptions(precision=4)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

## Question 1
Out of 500 students, 410 students pass the exam. Test the hypothesis that more than 80% of students pass the exam. Level of significance = 5%

**Solution:**

In [29]:
# Question 1: Hypothesis Testing for Proportion (One-tailed test)
# H0: p = 0.80
# H1: p > 0.80 (One-tailed test)

n1 = 500  # sample size
x1 = 410  # number of students who passed
p1_sample = x1 / n1  # sample proportion
P1 = 0.80  # hypothesized proportion
alpha1 = 0.05  # level of significance

# Calculate test statistic
SE1 = math.sqrt(P1 * (1 - P1) / n1)
z1 = (p1_sample - P1) / SE1

# Critical value for one-tailed test (right tail)
z_critical1 = norm.ppf(1 - alpha1)
p_value1 = 1 - norm.cdf(z1)

print("Question 1: Hypothesis Testing for Proportion")
print("=" * 60)
print(f"Sample size (n): {n1}")
print(f"Number passed: {x1}")
print(f"Sample proportion (p̂): {p1_sample}")
print(f"Hypothesized proportion (P): {P1}")
print(f"Level of significance (α): {alpha1}")
print(f"\nStandard Error: {SE1:.6f}")
print(f"Test statistic (z): {z1:.6f}")
print(f"Critical value (z_α): {z_critical1:.6f}")
print(f"P-value: {p_value1:.6f}")
print(f"\nDecision: ", end="")
if z1 > z_critical1:
    print(f"REJECT H0 (z = {z1:.4f} > {z_critical1:.4f})")
    print("Conclusion: Yes, more than 80% of students pass the exam at 5% significance level.")
else:
    print(f"FAIL TO REJECT H0 (z = {z1:.4f} ≤ {z_critical1:.4f})")
    print("Conclusion: Not enough evidence to claim more than 80% of students pass the exam.")
print("=" * 60)

Question 1: Hypothesis Testing for Proportion
Sample size (n): 500
Number passed: 410
Sample proportion (p̂): 0.82
Hypothesized proportion (P): 0.8
Level of significance (α): 0.05

Standard Error: 0.017889
Test statistic (z): 1.118034
Critical value (z_α): 1.644854
P-value: 0.131776

Decision: FAIL TO REJECT H0 (z = 1.1180 ≤ 1.6449)
Conclusion: Not enough evidence to claim more than 80% of students pass the exam.


## Question 2
A random sample of 35 individuals selected from a certain population showed that 6 of them are left-handed. Find 95% and 99% confidence limits for the proportions of left-handed person in the population.

**Solution:**

In [30]:
# Question 2: Confidence Interval for Proportion
n2 = 35
x2 = 6
p2 = x2 / n2

# Standard error
SE2 = math.sqrt(p2 * (1 - p2) / n2)

# For 95% confidence (α = 0.05)
alpha_95 = 0.05
z_95 = norm.ppf(1 - alpha_95/2)
CI_95_lower = p2 - z_95 * SE2
CI_95_upper = p2 + z_95 * SE2

# For 99% confidence (α = 0.01)
alpha_99 = 0.01
z_99 = norm.ppf(1 - alpha_99/2)
CI_99_lower = p2 - z_99 * SE2
CI_99_upper = p2 + z_99 * SE2

print("\nQuestion 2: Confidence Interval for Proportion")
print("=" * 60)
print(f"Sample size (n): {n2}")
print(f"Left-handed individuals: {x2}")
print(f"Sample proportion (p̂): {p2:.6f}")
print(f"Standard Error: {SE2:.6f}")
print(f"\n95% Confidence Interval (z = {z_95:.4f}):")
print(f"  Lower limit: {CI_95_lower:.6f}")
print(f"  Upper limit: {CI_95_upper:.6f}")
print(f"  CI: [{CI_95_lower:.4f}, {CI_95_upper:.4f}]")
print(f"\n99% Confidence Interval (z = {z_99:.4f}):")
print(f"  Lower limit: {CI_99_lower:.6f}")
print(f"  Upper limit: {CI_99_upper:.6f}")
print(f"  CI: [{CI_99_lower:.4f}, {CI_99_upper:.4f}]")
print("=" * 60)


Question 2: Confidence Interval for Proportion
Sample size (n): 35
Left-handed individuals: 6
Sample proportion (p̂): 0.171429
Standard Error: 0.063705

95% Confidence Interval (z = 1.9600):
  Lower limit: 0.046569
  Upper limit: 0.296288
  CI: [0.0466, 0.2963]

99% Confidence Interval (z = 2.5758):
  Lower limit: 0.007336
  Upper limit: 0.335521
  CI: [0.0073, 0.3355]


## Question 3
The manufacturer of patent medicine claimed that it was 90% effective in relieving allergy for a period of 8 hours. In a sample of 200 people who had the allergy, the medicine provided relief for 160 people. Determine whether manufacturer's claim is legitimate.

**Solution:**

In [31]:
# Question 3: Hypothesis Testing for Proportion (Two-tailed test)
# H0: p = 0.90
# H1: p ≠ 0.90 (Two-tailed test)

n3 = 200
x3 = 160
p3_sample = x3 / n3
P3 = 0.90
alpha3 = 0.05  # Typical significance level

SE3 = math.sqrt(P3 * (1 - P3) / n3)
z3 = (p3_sample - P3) / SE3

z_critical3 = norm.ppf(1 - alpha3/2)
p_value3 = 2 * (1 - norm.cdf(abs(z3)))

print("\nQuestion 3: Manufacturer's Claim Verification")
print("=" * 60)
print(f"Sample size (n): {n3}")
print(f"People relieved: {x3}")
print(f"Sample proportion (p̂): {p3_sample}")
print(f"Claimed proportion (P): {P3}")
print(f"Level of significance (α): {alpha3}")
print(f"\nStandard Error: {SE3:.6f}")
print(f"Test statistic (z): {z3:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical3:.6f}")
print(f"P-value: {p_value3:.6f}")
print(f"\nDecision: ", end="")
if abs(z3) > z_critical3:
    print(f"REJECT H0 (|z| = {abs(z3):.4f} > {z_critical3:.4f})")
    print("Conclusion: The manufacturer's claim is NOT legitimate at 5% significance level.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z3):.4f} ≤ {z_critical3:.4f})")
    print("Conclusion: The manufacturer's claim is legitimate at 5% significance level.")
print("=" * 60)


Question 3: Manufacturer's Claim Verification
Sample size (n): 200
People relieved: 160
Sample proportion (p̂): 0.8
Claimed proportion (P): 0.9
Level of significance (α): 0.05

Standard Error: 0.021213
Test statistic (z): -4.714045
Critical value (±z_α/2): ±1.959964
P-value: 0.000002

Decision: REJECT H0 (|z| = 4.7140 > 1.9600)
Conclusion: The manufacturer's claim is NOT legitimate at 5% significance level.


## Question 4
From one class of 500 students, 410 students passed. From other class of 400 students, 379 students passed. Test the hypothesis that both samples have same proportions. Level of significance = 0.025

**Solution:**

In [32]:
# Question 4: Hypothesis Testing for Difference of Two Proportions
# H0: p1 = p2
# H1: p1 ≠ p2 (Two-tailed test)

n4_1 = 500
x4_1 = 410
p4_1 = x4_1 / n4_1

n4_2 = 400
x4_2 = 379
p4_2 = x4_2 / n4_2

alpha4 = 0.025

# Pooled proportion
p_pool = (x4_1 + x4_2) / (n4_1 + n4_2)

# Standard error for difference of proportions
SE4 = math.sqrt(p_pool * (1 - p_pool) * (1/n4_1 + 1/n4_2))

# Test statistic
z4 = (p4_1 - p4_2) / SE4

# Critical value
z_critical4 = norm.ppf(1 - alpha4/2)
p_value4 = 2 * (1 - norm.cdf(abs(z4)))

print("\nQuestion 4: Testing Equality of Two Proportions")
print("=" * 60)
print(f"Class 1 - Sample size: {n4_1}, Passed: {x4_1}, Proportion: {p4_1:.6f}")
print(f"Class 2 - Sample size: {n4_2}, Passed: {x4_2}, Proportion: {p4_2:.6f}")
print(f"Pooled proportion (p̂): {p_pool:.6f}")
print(f"Level of significance (α): {alpha4}")
print(f"\nStandard Error: {SE4:.6f}")
print(f"Test statistic (z): {z4:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical4:.6f}")
print(f"P-value: {p_value4:.6f}")
print(f"\nDecision: ", end="")
if abs(z4) > z_critical4:
    print(f"REJECT H0 (|z| = {abs(z4):.4f} > {z_critical4:.4f})")
    print("Conclusion: The two samples have different proportions.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z4):.4f} ≤ {z_critical4:.4f})")
    print("Conclusion: The two samples have the same proportions at 2.5% significance level.")
print("=" * 60)


Question 4: Testing Equality of Two Proportions
Class 1 - Sample size: 500, Passed: 410, Proportion: 0.820000
Class 2 - Sample size: 400, Passed: 379, Proportion: 0.947500
Pooled proportion (p̂): 0.876667
Level of significance (α): 0.025

Standard Error: 0.022058
Test statistic (z): -5.780248
Critical value (±z_α/2): ±2.241403
P-value: 0.000000

Decision: REJECT H0 (|z| = 5.7802 > 2.2414)
Conclusion: The two samples have different proportions.


## Question 5
Two groups, A and B, each consists of 100 people who have a disease. A serum is given to group A but not group B; otherwise both the groups are treated identically. It's found that in group A and group B, 75 and 65 people respectively, recover from the disease. Test the hypothesis that serum helps to cure the disease using a level of significance (a) 0.01 (b) 0.1.

**Solution:**

In [33]:
# Question 5: Hypothesis Testing for Serum Effectiveness (One-tailed test)
# H0: p_A = p_B (Serum has no effect)
# H1: p_A > p_B (Serum helps to cure)

n5_A = 100
x5_A = 75
p5_A = x5_A / n5_A

n5_B = 100
x5_B = 65
p5_B = x5_B / n5_B

# Pooled proportion
p_pool5 = (x5_A + x5_B) / (n5_A + n5_B)

# Standard error for difference of proportions
SE5 = math.sqrt(p_pool5 * (1 - p_pool5) * (1/n5_A + 1/n5_B))

# Test statistic
z5 = (p5_A - p5_B) / SE5

# For α = 0.01
alpha5_a = 0.01
z_critical5_a = norm.ppf(1 - alpha5_a)
p_value5_a = 1 - norm.cdf(z5)

# For α = 0.1
alpha5_b = 0.1
z_critical5_b = norm.ppf(1 - alpha5_b)
p_value5_b = 1 - norm.cdf(z5)

print("\nQuestion 5: Testing Serum Effectiveness")
print("=" * 60)
print(f"Group A (with serum) - n: {n5_A}, Recovered: {x5_A}, Proportion: {p5_A:.4f}")
print(f"Group B (without serum) - n: {n5_B}, Recovered: {x5_B}, Proportion: {p5_B:.4f}")
print(f"Difference in proportions: {p5_A - p5_B:.4f}")
print(f"Pooled proportion: {p_pool5:.4f}")
print(f"Standard Error: {SE5:.6f}")
print(f"Test statistic (z): {z5:.6f}")
print(f"P-value: {p_value5_a:.6f}")

print(f"\n(a) Level of significance α = {alpha5_a}")
print(f"    Critical value (z_α): {z_critical5_a:.6f}")
print(f"    Decision: ", end="")
if z5 > z_critical5_a:
    print(f"REJECT H0 (z = {z5:.4f} > {z_critical5_a:.4f})")
    print(f"    Conclusion: Serum helps to cure the disease at 1% significance level.")
else:
    print(f"FAIL TO REJECT H0 (z = {z5:.4f} ≤ {z_critical5_a:.4f})")
    print(f"    Conclusion: Not enough evidence that serum helps at 1% significance level.")

print(f"\n(b) Level of significance α = {alpha5_b}")
print(f"    Critical value (z_α): {z_critical5_b:.6f}")
print(f"    Decision: ", end="")
if z5 > z_critical5_b:
    print(f"REJECT H0 (z = {z5:.4f} > {z_critical5_b:.4f})")
    print(f"    Conclusion: Serum helps to cure the disease at 10% significance level.")
else:
    print(f"FAIL TO REJECT H0 (z = {z5:.4f} ≤ {z_critical5_b:.4f})")
    print(f"    Conclusion: Not enough evidence that serum helps at 10% significance level.")
print("=" * 60)


Question 5: Testing Serum Effectiveness
Group A (with serum) - n: 100, Recovered: 75, Proportion: 0.7500
Group B (without serum) - n: 100, Recovered: 65, Proportion: 0.6500
Difference in proportions: 0.1000
Pooled proportion: 0.7000
Standard Error: 0.064807
Test statistic (z): 1.543033
P-value: 0.061411

(a) Level of significance α = 0.01
    Critical value (z_α): 2.326348
    Decision: FAIL TO REJECT H0 (z = 1.5430 ≤ 2.3263)
    Conclusion: Not enough evidence that serum helps at 1% significance level.

(b) Level of significance α = 0.1
    Critical value (z_α): 1.281552
    Decision: REJECT H0 (z = 1.5430 > 1.2816)
    Conclusion: Serum helps to cure the disease at 10% significance level.


## Question 6
Check the hypothesis that blood pressure before treatment has a mean value of 156 for the given dataset.

**Solution:**

In [34]:
# Question 6: Hypothesis Testing for Mean - Blood Pressure Before Treatment
# H0: μ = 156
# H1: μ ≠ 156 (Two-tailed test)

# Load blood pressure data
bp_data = pd.read_csv('blood_pressure.csv')
print("\nBlood Pressure Dataset Info:")
print(bp_data.head())
print(f"Dataset shape: {bp_data.shape}")

# Extract 'before' blood pressure column
BP_before = bp_data['bp_before'].dropna()

n6 = len(BP_before)
mean6 = BP_before.mean()
std6 = BP_before.std()  # sample standard deviation
mu6 = 156
alpha6 = 0.05

# Test statistic (using z-test for large samples)
SE6 = std6 / math.sqrt(n6)
z6 = (mean6 - mu6) / SE6

# Critical value (two-tailed)
z_critical6 = norm.ppf(1 - alpha6/2)
p_value6 = 2 * (1 - norm.cdf(abs(z6)))

print("\nQuestion 6: Blood Pressure Before Treatment")
print("=" * 60)
print(f"Sample size (n): {n6}")
print(f"Sample mean (x̄): {mean6:.4f}")
print(f"Sample standard deviation (s): {std6:.4f}")
print(f"Hypothesized mean (μ): {mu6}")
print(f"Level of significance (α): {alpha6}")
print(f"\nStandard Error: {SE6:.6f}")
print(f"Test statistic (z): {z6:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical6:.6f}")
print(f"P-value: {p_value6:.6f}")
print(f"\nDecision: ", end="")
if abs(z6) > z_critical6:
    print(f"REJECT H0 (|z| = {abs(z6):.4f} > {z_critical6:.4f})")
    print(f"Conclusion: Blood pressure mean is NOT 156 at 5% significance level.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z6):.4f} ≤ {z_critical6:.4f})")
    print(f"Conclusion: Blood pressure mean is 156 at 5% significance level.")
print("=" * 60)


Blood Pressure Dataset Info:
   patient   sex agegrp  bp_before  bp_after
0        1  Male  30-45        143       153
1        2  Male  30-45        163       170
2        3  Male  30-45        153       168
3        4  Male  30-45        153       142
4        5  Male  30-45        146       141
Dataset shape: (120, 5)

Question 6: Blood Pressure Before Treatment
Sample size (n): 120
Sample mean (x̄): 156.4500
Sample standard deviation (s): 11.3898
Hypothesized mean (μ): 156
Level of significance (α): 0.05

Standard Error: 1.039746
Test statistic (z): 0.432798
Critical value (±z_α/2): ±1.959964
P-value: 0.665161

Decision: FAIL TO REJECT H0 (|z| = 0.4328 ≤ 1.9600)
Conclusion: Blood pressure mean is 156 at 5% significance level.


## Question 7
Can we say that the systolic blood pressure measured on arm has mean value of 125 mmHg from the given dataset?

**Solution:**

In [35]:
# Question 7: Hypothesis Testing for Systolic Blood Pressure on Arm
# H0: μ = 125
# H1: μ ≠ 125 (Two-tailed test)

# Load systolic blood pressure data (on arm)
systolic_data = pd.read_csv('systolic blood pressure.csv')
print("\nSystolic Blood Pressure Dataset Info:")
print(systolic_data.head())
print(f"Dataset shape: {systolic_data.shape}")

# Extract the arm measurement column (usually first or second column)
BP_arm = systolic_data.iloc[:, 0].dropna()  # First column

n7 = len(BP_arm)
mean7 = BP_arm.mean()
std7 = BP_arm.std()
mu7 = 125
alpha7 = 0.05

# Test statistic
SE7 = std7 / math.sqrt(n7)
z7 = (mean7 - mu7) / SE7

# Critical value
z_critical7 = norm.ppf(1 - alpha7/2)
p_value7 = 2 * (1 - norm.cdf(abs(z7)))

print("\nQuestion 7: Systolic Blood Pressure on Arm")
print("=" * 60)
print(f"Sample size (n): {n7}")
print(f"Sample mean (x̄): {mean7:.4f}")
print(f"Sample standard deviation (s): {std7:.4f}")
print(f"Hypothesized mean (μ): {mu7}")
print(f"Level of significance (α): {alpha7}")
print(f"\nStandard Error: {SE7:.6f}")
print(f"Test statistic (z): {z7:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical7:.6f}")
print(f"P-value: {p_value7:.6f}")
print(f"\nDecision: ", end="")
if abs(z7) > z_critical7:
    print(f"REJECT H0 (|z| = {abs(z7):.4f} > {z_critical7:.4f})")
    print(f"Conclusion: We cannot say the mean systolic BP on arm is 125 mmHg.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z7):.4f} ≤ {z_critical7:.4f})")
    print(f"Conclusion: The mean systolic BP on arm is 125 mmHg at 5% significance level.")
print("=" * 60)


Systolic Blood Pressure Dataset Info:
   armsys  fingsys
0     140      154
1     110      112
2     138      156
3     124      152
4     142      142
Dataset shape: (200, 2)

Question 7: Systolic Blood Pressure on Arm
Sample size (n): 200
Sample mean (x̄): 128.5200
Sample standard deviation (s): 23.2876
Hypothesized mean (μ): 125
Level of significance (α): 0.05

Standard Error: 1.646680
Test statistic (z): 2.137634
Critical value (±z_α/2): ±1.959964
P-value: 0.032546

Decision: REJECT H0 (|z| = 2.1376 > 1.9600)
Conclusion: We cannot say the mean systolic BP on arm is 125 mmHg.


## Question 8
A sample of 50 pieces of certain type of string was tested. The mean breaking strength turned out to be 14.5 pounds. Test whether the sample is from a batch of string having mean breaking strength of 15.6 pounds and standard deviation of 2.2 pounds.

**Solution:**

In [36]:
# Question 8: Hypothesis Testing for String Breaking Strength
# H0: μ = 15.6 (sample is from the batch)
# H1: μ ≠ 15.6 (sample is not from the batch)

n8 = 50
mean8_sample = 14.5
mu8 = 15.6  # population mean
sigma8 = 2.2  # population standard deviation
alpha8 = 0.05

# Standard error
SE8 = sigma8 / math.sqrt(n8)

# Test statistic
z8 = (mean8_sample - mu8) / SE8

# Critical value
z_critical8 = norm.ppf(1 - alpha8/2)
p_value8 = 2 * (1 - norm.cdf(abs(z8)))

print("\nQuestion 8: Test String Breaking Strength")
print("=" * 60)
print(f"Sample size (n): {n8}")
print(f"Sample mean (x̄): {mean8_sample} pounds")
print(f"Population mean (μ): {mu8} pounds")
print(f"Population standard deviation (σ): {sigma8} pounds")
print(f"Level of significance (α): {alpha8}")
print(f"\nStandard Error: {SE8:.6f}")
print(f"Test statistic (z): {z8:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical8:.6f}")
print(f"P-value: {p_value8:.6f}")
print(f"\nDecision: ", end="")
if abs(z8) > z_critical8:
    print(f"REJECT H0 (|z| = {abs(z8):.4f} > {z_critical8:.4f})")
    print(f"Conclusion: The sample is NOT from a batch with mean 15.6 pounds.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z8):.4f} ≤ {z_critical8:.4f})")
    print(f"Conclusion: The sample is from a batch with mean 15.6 pounds at 5% significance level.")
print("=" * 60)


Question 8: Test String Breaking Strength
Sample size (n): 50
Sample mean (x̄): 14.5 pounds
Population mean (μ): 15.6 pounds
Population standard deviation (σ): 2.2 pounds
Level of significance (α): 0.05

Standard Error: 0.311127
Test statistic (z): -3.535534
Critical value (±z_α/2): ±1.959964
P-value: 0.000407

Decision: REJECT H0 (|z| = 3.5355 > 1.9600)
Conclusion: The sample is NOT from a batch with mean 15.6 pounds.


## Question 9
Check the hypothesis that mean value of systolic blood pressure measured on arm and finger are the same.

**Solution:**

In [37]:
# Question 9: Hypothesis Testing for Difference of Two Means (Arm vs Finger)
# H0: μ_arm = μ_finger
# H1: μ_arm ≠ μ_finger (Two-tailed test)

# Load systolic blood pressure data
systolic_data9 = pd.read_csv('systolic blood pressure.csv')

# Extract arm and finger measurements
# Assuming columns are: Arm, Finger (or similar)
print("\nColumn names:", systolic_data9.columns.tolist())
BP_arm9 = systolic_data9.iloc[:, 0].dropna()  # First column (arm)
if systolic_data9.shape[1] > 1:
    BP_finger9 = systolic_data9.iloc[:, 1].dropna()  # Second column (finger)
else:
    BP_finger9 = systolic_data['before'].dropna()  # fallback

n9_arm = len(BP_arm9)
mean9_arm = BP_arm9.mean()
std9_arm = BP_arm9.std()

n9_finger = len(BP_finger9)
mean9_finger = BP_finger9.mean()
std9_finger = BP_finger9.std()

alpha9 = 0.05

# Pooled standard deviation (assuming equal variances)
sp9 = math.sqrt(((n9_arm - 1) * std9_arm**2 + (n9_finger - 1) * std9_finger**2) / (n9_arm + n9_finger - 2))

# Standard error for difference of means
SE9 = sp9 * math.sqrt(1/n9_arm + 1/n9_finger)

# Test statistic
z9 = (mean9_arm - mean9_finger) / SE9

# Critical value
z_critical9 = norm.ppf(1 - alpha9/2)
p_value9 = 2 * (1 - norm.cdf(abs(z9)))

print("\nQuestion 9: Systolic BP - Arm vs Finger")
print("=" * 60)
print(f"Arm measurements:")
print(f"  Sample size: {n9_arm}, Mean: {mean9_arm:.4f}, Std Dev: {std9_arm:.4f}")
print(f"Finger measurements:")
print(f"  Sample size: {n9_finger}, Mean: {mean9_finger:.4f}, Std Dev: {std9_finger:.4f}")
print(f"Mean difference: {mean9_arm - mean9_finger:.4f}")
print(f"Level of significance (α): {alpha9}")
print(f"\nPooled Std Dev: {sp9:.6f}")
print(f"Standard Error: {SE9:.6f}")
print(f"Test statistic (z): {z9:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical9:.6f}")
print(f"P-value: {p_value9:.6f}")
print(f"\nDecision: ", end="")
if abs(z9) > z_critical9:
    print(f"REJECT H0 (|z| = {abs(z9):.4f} > {z_critical9:.4f})")
    print(f"Conclusion: Mean BP on arm and finger are DIFFERENT.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z9):.4f} ≤ {z_critical9:.4f})")
    print(f"Conclusion: Mean BP on arm and finger are the SAME at 5% significance level.")
print("=" * 60)


Column names: ['armsys', 'fingsys']

Question 9: Systolic BP - Arm vs Finger
Arm measurements:
  Sample size: 200, Mean: 128.5200, Std Dev: 23.2876
Finger measurements:
  Sample size: 200, Mean: 132.8150, Std Dev: 25.6482
Mean difference: -4.2950
Level of significance (α): 0.05

Pooled Std Dev: 24.496337
Standard Error: 2.449634
Test statistic (z): -1.753323
Critical value (±z_α/2): ±1.959964
P-value: 0.079547

Decision: FAIL TO REJECT H0 (|z| = 1.7533 ≤ 1.9600)
Conclusion: Mean BP on arm and finger are the SAME at 5% significance level.


## Question 10
The mean consumption of food grains among 400 samples middle class consumers is 380 grams per day per person with a standard deviation of 120 grams. A similar sample survey of 600 working class consumers gave a mean of 410 grams with standard deviation of 80 grams. Are we justified in saying that the difference between the averages of the two classes is 40? Use 5% level of significance.

**Solution:**

In [38]:
# Question 10: Hypothesis Testing for Difference of Two Means (Food Grain Consumption)
# H0: μ1 - μ2 = 40 (difference is 40 grams)
# H1: μ1 - μ2 ≠ 40 (difference is not 40 grams)

n10_middle = 400
mean10_middle = 380
std10_middle = 120

n10_working = 600
mean10_working = 410
std10_working = 80

alpha10 = 0.05
hypothesized_diff = 40  # We're testing if difference = 40

# Actual difference
actual_diff = mean10_middle - mean10_working  # 380 - 410 = -30

# Standard error
SE10 = math.sqrt((std10_middle**2 / n10_middle) + (std10_working**2 / n10_working))

# Test statistic: z = (actual difference - hypothesized difference) / SE
z10 = (actual_diff - hypothesized_diff) / SE10

# Critical value
z_critical10 = norm.ppf(1 - alpha10/2)
p_value10 = 2 * (1 - norm.cdf(abs(z10)))

print("\nQuestion 10: Food Grain Consumption - Middle Class vs Working Class")
print("=" * 60)
print(f"Middle Class Consumers:")
print(f"  Sample size: {n10_middle}, Mean: {mean10_middle} g, Std Dev: {std10_middle} g")
print(f"Working Class Consumers:")
print(f"  Sample size: {n10_working}, Mean: {mean10_working} g, Std Dev: {std10_working} g")
print(f"\nActual difference in means: {actual_diff} grams")
print(f"Hypothesized difference: {hypothesized_diff} grams")
print(f"Level of significance (α): {alpha10}")
print(f"\nStandard Error: {SE10:.6f}")
print(f"Test statistic (z): {z10:.6f}")
print(f"Critical value (±z_α/2): ±{z_critical10:.6f}")
print(f"P-value: {p_value10:.6f}")
print(f"\nDecision: ", end="")
if abs(z10) > z_critical10:
    print(f"REJECT H0 (|z| = {abs(z10):.4f} > {z_critical10:.4f})")
    print(f"Conclusion: We are NOT justified in saying the difference is 40 grams.")
    print(f"The actual difference ({actual_diff} g) is significantly different from 40 g.")
else:
    print(f"FAIL TO REJECT H0 (|z| = {abs(z10):.4f} ≤ {z_critical10:.4f})")
    print(f"Conclusion: We are justified in saying the difference is 40 grams at 5% significance level.")
print("=" * 60)


Question 10: Food Grain Consumption - Middle Class vs Working Class
Middle Class Consumers:
  Sample size: 400, Mean: 380 g, Std Dev: 120 g
Working Class Consumers:
  Sample size: 600, Mean: 410 g, Std Dev: 80 g

Actual difference in means: -30 grams
Hypothesized difference: 40 grams
Level of significance (α): 0.05

Standard Error: 6.831301
Test statistic (z): -10.246951
Critical value (±z_α/2): ±1.959964
P-value: 0.000000

Decision: REJECT H0 (|z| = 10.2470 > 1.9600)
Conclusion: We are NOT justified in saying the difference is 40 grams.
The actual difference (-30 g) is significantly different from 40 g.


## Question 11
Two populations have same mean but the standard deviation of one is twice that of the other. Show that in samples, each of size 500, drawn under simple random conditions, the difference of the means will not exceed $0.3\sigma$, where $\sigma$ is the smaller standard deviation.

**Solution:**

In [39]:
# Question 11: Theoretical Problem - Difference of Means with Different Standard Deviations

print("\nQuestion 11: Difference of Means with Different Standard Deviations")
print("=" * 60)
print("Theoretical Analysis:")
print("-" * 60)

print("""
Given:
- Two populations with the same mean μ
- Population 1 has standard deviation σ₁ = σ
- Population 2 has standard deviation σ₂ = 2σ
- Both samples have size n = 500

To Show: The difference of sample means will not exceed 0.3σ

Solution:

For large samples drawn from normal populations, the sampling distribution 
of the difference of means (x̄₁ - x̄₂) is approximately normal with:

Mean: μ₁ - μ₂ = μ - μ = 0 (given that populations have same mean)

Standard Error: SE = √(σ₁²/n₁ + σ₂²/n₂)
                   = √(σ²/500 + (2σ)²/500)
                   = √(σ²/500 + 4σ²/500)
                   = √(5σ²/500)
                   = √(σ²/100)
                   = σ/10

For a 95% confidence interval (z = 1.96):
The difference of means ≈ 1.96 × (σ/10) = 0.196σ ≈ 0.2σ

For a 99.7% confidence interval (z = 3, i.e., 3σ rule):
The difference of means ≈ 3 × (σ/10) = 0.3σ

Therefore, with 99.7% confidence, the difference of sample means 
will not exceed 0.3σ.

This can also be expressed as:
|x̄₁ - x̄₂| ≤ 0.3σ with very high probability (99.7%)
""")

# Numerical Verification
print("-" * 60)
print("Numerical Verification:")
print("-" * 60)

n11 = 500
sigma11 = 1  # Let σ = 1 for simplicity
sigma1_11 = sigma11
sigma2_11 = 2 * sigma11

# Standard error
SE11 = math.sqrt((sigma1_11**2 / n11) + (sigma2_11**2 / n11))
print(f"Standard Error (SE) = σ/10 = {SE11:.6f}")

# z-score for different confidence levels
z_90 = norm.ppf(0.95)  # 90% confidence
z_95 = norm.ppf(0.975)  # 95% confidence
z_99_7 = 3  # 99.7% confidence (3-sigma rule)

# Expected maximum difference
max_diff_90 = z_90 * SE11
max_diff_95 = z_95 * SE11
max_diff_99_7 = z_99_7 * SE11

print(f"\n90% Confidence level (z = {z_90:.4f}):")
print(f"  Maximum difference ≈ {max_diff_90:.6f}σ")

print(f"\n95% Confidence level (z = {z_95:.4f}):")
print(f"  Maximum difference ≈ {max_diff_95:.6f}σ")

print(f"\n99.7% Confidence level (z = {z_99_7:.4f}):")
print(f"  Maximum difference ≈ {max_diff_99_7:.6f}σ ≈ 0.3σ")

print(f"\n✓ Hence proved: With 99.7% confidence, |x̄₁ - x̄₂| ≤ 0.3σ")

# Simulation to verify
print("-" * 60)
print("Monte Carlo Simulation Verification:")
print("-" * 60)

np.random.seed(42)
num_simulations = 10000
differences = []

for _ in range(num_simulations):
    sample1 = np.random.normal(0, sigma1_11, n11)
    sample2 = np.random.normal(0, sigma2_11, n11)
    diff = sample1.mean() - sample2.mean()
    differences.append(diff)

differences = np.array(differences)
max_observed_diff = np.max(np.abs(differences))
percentile_99_7 = np.percentile(np.abs(differences), 99.7)

print(f"From {num_simulations} simulations:")
print(f"  Maximum observed difference: {max_observed_diff:.6f}σ")
print(f"  99.7th percentile of |differences|: {percentile_99_7:.6f}σ")
print(f"  0.3σ threshold: 0.3")
print(f"\n✓ Simulation confirms: ~99.7% of differences are within 0.3σ")

print("=" * 60)


Question 11: Difference of Means with Different Standard Deviations
Theoretical Analysis:
------------------------------------------------------------

Given:
- Two populations with the same mean μ
- Population 1 has standard deviation σ₁ = σ
- Population 2 has standard deviation σ₂ = 2σ
- Both samples have size n = 500

To Show: The difference of sample means will not exceed 0.3σ

Solution:

For large samples drawn from normal populations, the sampling distribution 
of the difference of means (x̄₁ - x̄₂) is approximately normal with:

Mean: μ₁ - μ₂ = μ - μ = 0 (given that populations have same mean)

Standard Error: SE = √(σ₁²/n₁ + σ₂²/n₂)
                   = √(σ²/500 + (2σ)²/500)
                   = √(σ²/500 + 4σ²/500)
                   = √(5σ²/500)
                   = √(σ²/100)
                   = σ/10

For a 95% confidence interval (z = 1.96):
The difference of means ≈ 1.96 × (σ/10) = 0.196σ ≈ 0.2σ

For a 99.7% confidence interval (z = 3, i.e., 3σ rule):
The difference of mea

## Conclusion

In this experiment, we successfully studied and implemented hypothesis testing for both proportions and means for large samples. 

### Key Learnings:

1. **Hypothesis Testing for Proportions:**
   - Used z-test for large samples (n ≥ 30)
   - Tested one-tailed and two-tailed hypotheses
   - Calculated confidence intervals for proportions

2. **Hypothesis Testing for Means:**
   - Applied z-test when population standard deviation is known
   - Tested single population means vs. hypothesized values
   - Tested differences between two population means

3. **Decision Rules:**
   - Compared test statistics with critical values at specified significance levels
   - Used p-values to make statistical conclusions
   - Understood Type I and Type II error concepts

4. **Applications:**
   - Real-world problems involving medical treatments, educational assessments, manufacturing, and consumer behavior
   - Demonstrated importance of statistical testing in validating claims

### Summary of Tested Questions:
- **Q1-Q5**: Proportion testing (single and two samples)
- **Q6-Q9**: Mean testing for single and paired samples
- **Q10**: Testing equality of differences between means
- **Q11**: Theoretical analysis of sampling distributions

Thus, we studied hypothesis testing for proportion and mean for large samples and successfully solved practical problems using Python and statistical theory.